apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db-h
  replicas: 2
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: bcdscrypto/devopstest-db:latest
        env:
          - name: MONGO_INITDB_HOST
            value: db-h
          - name: MONGO_INITDB_DATABASE
            value: animal_db
          - name: MONGO_INITDB_ROOT_USERNAME
            value: root
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: pass
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-volume
          mountPath: /data/db
  volumeClaimTemplates:
  - metadata:
      name: mongo-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
