apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
spec:
  selector:
    matchLabels:
      app: db
  serviceName: db-h
  replicas: 1
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: postgres
        envFrom:
          - secretRef:
              name: db-secret
        # env:
        #   - name: POSTGRES_DB
        #     value: realestate
        #   - name: POSTGRES_USER
        #     value: postgres
        #   - name: POSTGRES_PASSWORD
        #     value: postgres
        #   - name: PGPASSWORD
        #     value: pass
        volumeMounts:
        - name: db-volume
          mountPath: /var/lib/postgres
  volumeClaimTemplates:
  - metadata:
      name: db-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
